name: hello_try
on:
  workflow_dispatch: 
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello try
        run: echo "good try"

      - name: keep trying
        run: echo "keep tryinggg"
      
      

