name: run-test-script
on:
  workflow_dispatch:
jobs:
  script-running:
    runs-on: ubuntu-latest
    steps:
      - name: getting repo / checkout
        uses: actions/checkout@v4
      - name: running script and giving permission aswell to run script
        run: |
            chmod a+x ./scripts/test_script.sh
            ./scripts/test_script.sh
      
