name: show_repo_info
on:
  workflow_dispatch: 
jobs:
  info-check:
    runs-on: ubuntu-latest
    steps:
      - name: showing working directory
        run: pwd

      - name: showing ls
        run: ls

      - name: showing ls -la
        run: ls -la
      
      

